import React, { useState, useEffect } from 'react';
import { listAlerts, Alert, getAlertStats } from '../api/client';
import { RiskBadge } from '../components/RiskBadge';
import { ICN } from '../components/Icon';
import { ConfidenceBar } from '../components/ConfidenceBar';

function relTime(ts: number): string {
  const diff = Math.floor((Date.now() / 1000) - ts);
  if (diff < 60) return `${diff}s ago`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

const TABS = [
  { key: '', label: 'All Alerts', icon: ICN.bell },
  { key: 'active', label: 'Pending', icon: ICN.alert },
  { key: 'confirmed', label: 'Confirmed', icon: ICN.check },
  { key: 'dismissed', label: 'Dismissed', icon: ICN.x },
];

export function AlertsPage({ onOpenIncident }: { onOpenIncident: (alert: Alert) => void }) {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [stats, setStats] = useState<any>({});
  const [tab, setTab] = useState('');

  const loadAlerts = async () => {
    try {
      const [data, st] = await Promise.all([
        listAlerts({ status: tab || undefined }),
        getAlertStats()
      ]);
      setAlerts(data);
      setStats(st);
    } catch (err) {
      console.error('Error fetching alerts:', err);
    }
  };

  useEffect(() => { loadAlerts(); }, [tab]);

  const tabCounts: Record<string, number> = {
    '': stats.total || 0,
    'active': (stats.active || 0) + (stats.reviewing || 0),
    'confirmed': stats.confirmed || 0,
    'dismissed': stats.dismissed || 0,
  };

  return (
    <div className="fade-in">
      <div className="page-header">
        <div>
          <div className="page-title">Alert Center</div>
          <div className="page-sub">Review, confirm, or dismiss security alerts generated by RiskEngine</div>
        </div>
        <div className="page-actions">
          <button className="btn" onClick={loadAlerts}>
            {ICN.restart({ size: 14 })} Refresh
          </button>
        </div>
      </div>

      {/* Tab bar */}
      <div className="tabs-row" style={{ marginBottom: 16 }}>
        {TABS.map(t => (
          <div
            key={t.key}
            className={`tab-btn ${tab === t.key ? 'active' : ''}`}
            onClick={() => setTab(t.key)}
          >
            {t.icon({ size: 13 })} {t.label}
            {tabCounts[t.key] > 0 && (
              <span style={{ marginLeft: 6, fontSize: 10, fontFamily: 'var(--font-mono)', opacity: 0.7 }}>
                {tabCounts[t.key]}
              </span>
            )}
          </div>
        ))}
      </div>

      <div className="panel">
        <div className="panel-body" style={{ padding: 0 }}>
          <table className="data-table">
            <thead>
              <tr>
                <th style={{ width: 30 }}></th>
                <th>Alert ID</th>
                <th>Camera / Location</th>
                <th>Risk</th>
                <th>Score</th>
                <th>Signals</th>
                <th>Time</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={9} style={{ textAlign: 'center', padding: 30, color: 'var(--text-low)' }}>
                    {ICN.shield({ size: 24, style: { display: 'block', margin: '0 auto 8px', color: 'var(--safe)' } })}
                    No alerts match the current filter.
                  </td>
                </tr>
              ) : (
                alerts.map((al) => (
                  <tr key={al.id} onClick={() => onOpenIncident(al)}>
                    <td>
                      <span className={`dot ${al.risk_level === 'CRITICAL' ? 'critical' : al.risk_level === 'HIGH' ? 'high' : al.risk_level === 'ELEVATED' ? 'medium' : 'safe'}`} />
                    </td>
                    <td>
                      <span className="mono" style={{ fontWeight: 600, fontSize: 11.5 }}>{al.id}</span>
                    </td>
                    <td>
                      <div style={{ fontWeight: 600, fontSize: 12.5 }}>{al.camera_name}</div>
                      <div style={{ fontSize: 10.5, color: 'var(--text-low)' }}>{al.location}</div>
                    </td>
                    <td>
                      <RiskBadge risk={al.risk_level}>{al.risk_level}</RiskBadge>
                    </td>
                    <td>
                      <div className="mono" style={{ fontWeight: 700, fontSize: 14 }}>{al.risk_score?.toFixed(1)}</div>
                      <ConfidenceBar value={al.risk_score || 50} colorVar={
                        al.risk_level === 'CRITICAL' ? 'var(--critical)' :
                        al.risk_level === 'HIGH' ? 'var(--high)' :
                        al.risk_level === 'ELEVATED' ? 'var(--medium)' : 'var(--safe)'
                      } />
                    </td>
                    <td>
                      <div style={{ display: 'flex', flexWrap: 'wrap' as const, gap: 3 }}>
                        {al.types?.slice(0, 2).map((t, idx) => (
                          <span key={idx} className="chip" style={{ fontSize: 9.5 }}>{t}</span>
                        ))}
                        {(al.types?.length || 0) > 2 && (
                          <span className="chip" style={{ fontSize: 9.5 }}>+{al.types!.length - 2}</span>
                        )}
                      </div>
                    </td>
                    <td>
                      <span className="mono" style={{ fontSize: 11, color: 'var(--text-mid)' }}>
                        {relTime(al.timestamp)}
                      </span>
                    </td>
                    <td>
                      <span className={`badge ${al.status === 'confirmed' ? 'safe' : al.status === 'dismissed' ? 'neutral' : al.status === 'reviewing' ? 'info' : 'critical'}`}>
                        {al.status}
                      </span>
                    </td>
                    <td>
                      <button className="btn sm primary" onClick={(e) => { e.stopPropagation(); onOpenIncident(al); }}>
                        {ICN.eye({ size: 11 })} Inspect
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
